CREATE TABLE
    ARES_KEY_SEQUENCE
    (
        CODE VARCHAR2(64) NOT NULL,
        VALUE VARCHAR2(64),
        PRIMARY KEY (CODE)
    );
COMMENT ON TABLE ARES_KEY_SEQUENCE
IS
    '序列表';
COMMENT ON COLUMN ARES_KEY_SEQUENCE.CODE
IS
    '表名';
COMMENT ON COLUMN ARES_KEY_SEQUENCE.VALUE
IS
    '序列当前值';